# Generated by Django 2.2.2 on 2019-07-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20190708_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Текст статьи')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('products', models.ManyToManyField(to='store.Product', verbose_name='Связанные товары')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['order'],
            },
        ),
    ]
