# Generated by Django 2.2.2 on 2019-07-05 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20190705_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Section', verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='section',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Section', verbose_name='Родительский раздел'),
        ),
    ]
