# Generated by Django 2.2.2 on 2019-07-08 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20190705_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_parent': False}, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Section', verbose_name='Родительский раздел'),
        ),
    ]
