# Generated by Django 2.2.2 on 2019-07-11 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_orderline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderline',
            options={'verbose_name': 'Строка заказа', 'verbose_name_plural': 'Строки заказа'},
        ),
    ]
